### PR TITLE
roomba.py update

### PR DESCRIPTION
**Pull request by goooroooX**
Logging enhancement and fix for home-assistant.io.
I would also suggest to update PyPI repository.

### CODE REVIEW

**Comment by goooroooX** [comment]
Original exception in Home Assistant (after adding more traceback):
```
[I 2018-07-07 16:48:50,209] Error setting TLS: Traceback (most recent call last):
  File "/opt/homeassistant/lib64/python3.6/site-packages/roomba/roomba.py", line 264, in setup_client
    tls_version=ssl.PROTOCOL_TLSv1)
  File "/opt/homeassistant/lib64/python3.6/site-packages/paho/mqtt/client.py", line 702, in tls_set
    context.load_verify_locations(ca_certs)
FileNotFoundError: [Errno 2] No such file or directory

[E 2018-07-07 16:48:50,209] Error: Must configure SSL context before using tls_insecure_set.
```

**Comment by goooroooX** [comment]
https://community.home-assistant.io/t/irobot-roomba/6288/55?u=gooorooo

**Comment by zacs** [comment]
@NickWaterton any chance to get this merged soon? Roomba functionality is busted for Home Assistant folks at the moment. Thanks!

**Comment by NickWaterton** [comment]
OK, Done.

**Comment by zacs** [comment]
Thank you sir!

**Pull request merged**
