### PR TITLE
Minor Cleanup

### PR DESCRIPTION
**Pull request by pschmitt**
- Move the image files to a new `res` directory, which would make it easier to include in the `setup.py`. Right now the pip install would not install the images. I'll see to make that happen.
- Remove the `ca-certificates.crt` file. It may be convenient to host that here, but this here is not really its place. Let's at least default to the system one. BTW is is even really used?
- Update `.gitignore` to ignore Python 3 caches files and other Python stuff.

### CODE REVIEW

**Comment by NickWaterton** [comment]
> •Remove the  ca-certificates.crt  file. It may be convenient to host that here, but this here is not really its place. Let's at least default to the system one. BTW is is even really used?

In the latest paho-mqtt it's not used, in the old paho-mqtt is also not used, but is a required field (and has to be an actual certificate). If we use the system one, it assumes that you are using a version of Ubuntu where this is in the default location. As we know, things are always changing in Linux, and it wouldn't surprize me if this was randomly moved at some point. Also what about non-Linux OS's? (yes I know I haven't even tried to support other OS's, but you know).

**Comment by pschmitt** [comment]
I guess users that run into problems could still just set the certificate path to a real certificate. That's at least true for library users ie. users that use this code for programmatic communication with their Roombas.
Maybe we should expose a `--certificate CERT` CLI option?

**Comment by NickWaterton** [comment]
I think there are enough option already, as it's not used for the new version of paho-mqtt, it's really only an issue for old Ubuntu 14.04 users, in which case the default location should be OK. Probably best just leave it as you have set up.

**Comment by pschmitt** [comment]
Your call, I submitted the PR anyway.

**Pull request merged**
